// src/lib/hrms-icons.ts
//
// Lucide icon picker for CMS-managed HRMS modules. Admins type an icon name
// (same PascalCase names used across the codebase, e.g. "Sparkles"); the
// navbar resolves it here. Unknown/empty names fall back to LayoutGrid.

import {
  Users,
  Calculator,
  Calendar,
  CalendarDays,
  CalendarCheck,
  Plane,
  FileText,
  FileCheck,
  FilePlus,
  Clock,
  Timer,
  Hourglass,
  UserPlus,
  UserCheck,
  User,
  UsersRound,
  Contact,
  DollarSign,
  Percent,
  Wallet,
  Banknote,
  CreditCard,
  Receipt,
  PiggyBank,
  Shield,
  TrendingUp,
  TrendingDown,
  Briefcase,
  BarChart3,
  PieChart,
  Activity,
  BookOpen,
  BookMarked,
  GraduationCap,
  Smartphone,
  Code,
  Building2,
  Landmark,
  Newspaper,
  CheckSquare,
  BadgeCheck,
  Phone,
  Mail,
  MessageSquare,
  Bell,
  BookDown,
  Folder,
  Archive,
  ClipboardList,
  ClipboardCheck,
  Sparkles,
  Star,
  Heart,
  HeartPulse,
  Settings,
  Cog,
  Globe,
  Zap,
  Award,
  Target,
  Layers,
  LayoutGrid,
  LayoutDashboard,
  Info,
  Lightbulb,
  Rocket,
  Compass,
  Flag,
  Gift,
  Coffee,
  Fingerprint,
  KeyRound,
  Lock,
  Eye,
  Upload,
  Download,
  Search,
  SlidersHorizontal,
  Wrench,
  Puzzle,
  PenLine,
  Send,
  ThumbsUp,
  Umbrella,
  Scale,
  type LucideIcon,
} from "lucide-react";

const ICONS = {
  Users,
  Calculator,
  Calendar,
  CalendarDays,
  CalendarCheck,
  Plane,
  FileText,
  FileCheck,
  FilePlus,
  Clock,
  Timer,
  Hourglass,
  UserPlus,
  UserCheck,
  User,
  UsersRound,
  Contact,
  DollarSign,
  Percent,
  Wallet,
  Banknote,
  CreditCard,
  Receipt,
  PiggyBank,
  Shield,
  TrendingUp,
  TrendingDown,
  Briefcase,
  BarChart3,
  PieChart,
  Activity,
  BookOpen,
  BookMarked,
  GraduationCap,
  Smartphone,
  Code,
  Building2,
  Landmark,
  Newspaper,
  CheckSquare,
  BadgeCheck,
  Phone,
  Mail,
  MessageSquare,
  Bell,
  BookDown,
  Folder,
  Archive,
  ClipboardList,
  ClipboardCheck,
  Sparkles,
  Star,
  Heart,
  HeartPulse,
  Settings,
  Cog,
  Globe,
  Zap,
  Award,
  Target,
  Layers,
  LayoutGrid,
  LayoutDashboard,
  Info,
  Lightbulb,
  Rocket,
  Compass,
  Flag,
  Gift,
  Coffee,
  Fingerprint,
  KeyRound,
  Lock,
  Eye,
  Upload,
  Download,
  Search,
  SlidersHorizontal,
  Wrench,
  Puzzle,
  PenLine,
  Send,
  ThumbsUp,
  Umbrella,
  Scale,
};

const normalize = (s: string) => s.toLowerCase().replace(/[^a-z0-9]/g, "");

const BY_KEY: Record<string, LucideIcon> = {};
for (const [name, C] of Object.entries(ICONS)) BY_KEY[normalize(name)] = C;

/** Canonical PascalCase names, for the admin autocomplete list. */
export const HRMS_ICON_NAMES = Object.keys(ICONS).sort();

/** Resolve a typed name (case/format tolerant) to a component. */
export function resolveHrmsIcon(name: string | null | undefined): LucideIcon {
  if (!name) return LayoutGrid;
  return BY_KEY[normalize(name)] || LayoutGrid;
}
