-- HRMS CMS seed, extracted verbatim from the 20 static pages on 2026-09-12
-- (see docs/hrms-cms.md).
--
-- RUN ONCE (tracked by supabase_migrations under `db push`). Do NOT re-run
-- after staff edit content in /admin/hrms — it would duplicate feature rows.
-- To reset to this seed: TRUNCATE public.hrms_features, public.hrms_modules CASCADE;
-- then run this file (destroys all admin edits).
--
-- NOTE: leave-management rows are hand-written (its page uses
-- ModulePageLayout with media); the rest were script-extracted.
-- leave-management's custom blue CTA banner is static-only (not migrated).

-- leave-management (pageDescription + media features from pageData) --
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status) VALUES ('leave-management', 'Leave Management', 'Centralized leave tracking system managing entitlements, balances, approvals, and compliance with company policies, improving transparency and workforce planning efficiency.', '/images/hrsm-modules/leave_management.png', 'published')
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name, tagline = EXCLUDED.tagline, image_src = EXCLUDED.image_src, status = EXCLUDED.status, updated_at = now();
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, media_src, media_alt, bg_color, order_index) VALUES ('leave-management', 'Simple, Compliant, and Transparent', 'Managing employee leave can be complex, but our Leave Management module makes it effortless, transparent, and fully compliant with company policy and statutory regulations.', 'right-media', 'image', '/images/leave-management/centralized-records.jpg', 'Centralized leave records dashboard', 'bg-slate-50', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, media_src, media_alt, bg_color, order_index) VALUES ('leave-management', 'Centralized Leave Records', 'All leave applications, balances, and approvals are captured in one system, ensuring accurate, up-to-date records for easy tracking and reporting.', 'left-media', 'image', '/images/leave-management/centralized-records.jpg', 'Centralized leave records dashboard', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, media_src, media_alt, bg_color, order_index) VALUES ('leave-management', 'Policy Compliance Built-In', 'The module supports diverse leave types and rules are automated to enforce eligibility and statutory compliance across all departments.', 'right-media', 'image', '/images/leave-management/policy-compliance.jpg', 'Policy compliance interface', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, media_src, media_alt, bg_color, order_index) VALUES ('leave-management', 'Automated Workflow', 'Streamline your leave approval process with customizable workflows that route requests to the right managers automatically.', 'center', 'video', '/videos/leave-workflow-demo.mp4', '/images/leave-management/workflow-poster.jpg', 'bg-blue-50', 4);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, media_src, media_alt, bg_color, order_index) VALUES ('leave-management', 'Real-time Analytics', 'Get insights into leave patterns, team availability, and compliance metrics with comprehensive reporting tools.', 'full-width', 'image', '/images/leave-management/analytics-dashboard-wide.jpg', 'Analytics dashboard showing leave metrics', 'bg-gray-50', 5);
DELETE FROM public.hrms_features WHERE module_slug = 'leave-management' AND order_index > 5;

-- bulk seed (19 modules + 95 features, script-extracted) --
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status) VALUES ('ai-chatbot', 'AI Chatbot', '', '', 'draft');
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status, outro_text) VALUES ('personnel-hub', 'Personnel Hub', 'One-stop personnel hub delivering reliable employee data, improving collaboration between HR, managers, and leadership', '/images/hrsm-modules/personnel_hub.png', 'published', 'With Personnel Hub, your HR team gains a trusted, centralized, and future-ready foundation to manage your most valuable asset, your people.');
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('personnel-hub', 'The Core of Your HR System', 'At the heart of every HR solution lies the Personnel Hub, designed to centralize and safeguard all employee information in one secure, accessible place. It is the foundation upon which every other HR process is built.', 'center', 'none', 'bg-white', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('personnel-hub', 'Centralized Employee Records', 'Personnel Hub ensures that every employee detail—from personal information and employment history to job assignments and benefits—is captured, organized, and always up to date. No more scattered files or siloed systems; everything lives in one reliable source of truth.', 'center', 'none', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('personnel-hub', 'Smarter Data Management', 'With its intuitive structure, the module enables HR teams to quickly access records, generate reports, and comply with statutory requirements. It reduces duplication, minimizes errors, and ensures consistency across payroll, leave, claims, and performance management.', 'center', 'none', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('personnel-hub', 'Supporting Growth and Scalability', 'As your organization evolves, Personnel Hub scales with you. New employees, roles, and departments can be seamlessly added, keeping the system aligned with your business structure.', 'center', 'none', 'bg-slate-50', 4);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('personnel-hub', 'Foundation for Integration', 'Because it underpins every other module—Payroll, Leave, Training, Performance—the Personnel Hub is not just a database, but the backbone of the entire HR ecosystem, enabling smooth cross-module integration and reliable decision-making.', 'center', 'none', 'bg-white', 5);
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status, outro_text) VALUES ('payroll-management', 'Payroll Management', 'Automated payroll system streamlining salary processing, statutory compliance, deductions, and allowances, ensuring accurate, timely, and secure payment for employees.', '/images/hrsm-modules/payroll_management.png', 'published', 'With Payroll Management, you can ensure timely, accurate, and compliant salary disbursement, strengthen employee trust while reducing administrative burden.');
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('payroll-management', 'Accurate, Compliant, and On Time', 'Payroll is one of the most critical HR functions, and our Payroll Management module ensures it is handled with precision, compliance, and efficiency every single time.', 'center', 'none', 'bg-white', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('payroll-management', 'Streamlined Payroll Workflows', 'Designed to simplify complex calculations, the module automates salary processing, tax deductions, statutory contributions, and allowances. By minimizing manual effort, HR teams can focus on accuracy rather than repetitive tasks.', 'center', 'none', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('payroll-management', 'Compliance Made Easy', 'Payroll Management is built to meet Malaysia’s statutory requirements, including EPF, SOCSO, EIS, and PCB. Automatic updates to statutory tables ensure your organization remains compliant without extra effort.', 'center', 'none', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('payroll-management', 'Flexibility for Every Organization', 'Whether you are handling multiple pay groups, variable allowances, bonuses, or overtime, the system adapts seamlessly to different payroll policies and structures. It supports a wide range of industries and workforce types.', 'center', 'none', 'bg-slate-50', 4);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('payroll-management', 'Integrated with the HR Ecosystem', 'Because Payroll is fully integrated with Personnel Hub, Time & Attendance, and Leave Management, it eliminates data silos and ensures that all calculations reflect real-time updates from across the HR system.', 'center', 'none', 'bg-white', 5);
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status, outro_text) VALUES ('leave-passage', 'Leave Passage', 'Exclusive benefit module enabling organizations to reward employees with paid vacation entitlements, enhancing satisfaction, loyalty, and long-term workforce commitment.', '/images/hrsm-modules/leave_passage.png', 'published', 'With Leave Passage, organizations can offer unique, policy-driven travel benefits that go beyond compliance—creating stronger bonds between employees and the company.');
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('leave-passage', 'Rewarding Employees with Travel Benefits', 'Beyond standard leave entitlements, our Leave Passage module helps organizations recognize and reward employees with travel benefits that foster loyalty and satisfaction.', 'center', 'none', 'bg-white', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('leave-passage', 'Exclusive Employee Benefit', 'Leave Passage allows employees to enjoy fully paid vacation entitlements, typically covering airfare or travel packages. This benefit is often extended based on seniority or years of service, making it a symbol of recognition and appreciation.', 'center', 'none', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('leave-passage', 'Policy-Driven Flexibility', 'The module accommodates varying eligibility criteria and entitlements according to organizational policies. Whether based on grading, length of service, or specific agreements, rules can be configured to ensure fairness and compliance.', 'center', 'none', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('leave-passage', 'Streamlined Administration', 'HR teams can manage entitlements, track usage, and generate reports to monitor benefit utilization. By automating these processes, the system reduces administrative workload and ensures accuracy.', 'center', 'none', 'bg-slate-50', 4);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('leave-passage', 'Enhancing Employee Engagement', 'More than a financial perk, Leave Passage promotes employee well-being, strengthens retention, and supports a positive work culture by recognizing contributions in a meaningful way.', 'center', 'none', 'bg-white', 5);
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status, outro_text) VALUES ('claims-management', 'Claims Management', 'Streamlined claims submission and approval process with built-in validations, ensuring faster reimbursements, transparency, and reduced administrative workload for HR teams.', '/images/hrsm-modules/claim_management.png', 'published', 'With Claims Management, organizations can accelerate expense reimbursements, reduce administrative work, and strengthen policy compliance, while employees benefit from faster, hassle-free claim settlements.');
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('claims-management', 'Simplifying Expense Reimbursements', 'Managing employee claims can often be time-consuming and prone to errors. Our Claims Management module streamlines the entire process, ensuring faster reimbursements with clear accountability.', 'center', 'none', 'bg-white', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('claims-management', 'Centralized Claim Processing', 'Employees can easily submit claims for travel, meals, medical, or other business expenses. All submissions are captured in one place, reducing paperwork and manual tracking.', 'center', 'none', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('claims-management', 'Automated Policy Enforcement', 'Built-in rules help enforce company policies—covering claim categories, limits, and eligibility. This minimizes discrepancies, prevents over-claims, and ensures compliance with both internal policies and statutory requirements.', 'center', 'none', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('claims-management', 'Smooth Approval Workflows', 'Configurable approval routes allow claims to flow seamlessly from employee to manager, with notifications keeping the process efficient and transparent. Delays are reduced, and accountability is clear.', 'center', 'none', 'bg-slate-50', 4);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('claims-management', 'Integrated with Payroll', 'Approved claims feed directly into Payroll Management, ensuring timely and accurate reimbursements. No double entry, no missed payments—just clean, integrated data.', 'center', 'none', 'bg-white', 5);
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status, outro_text) VALUES ('time-attendance', 'Time & Attendance', 'Real-time attendance tracking with clock-in/out integrations, improving accuracy, workforce visibility, and compliance while reducing errors and manual HR intervention.', '/images/hrsm-modules/time_and_attendance.png', 'published', 'With Time & Attendance, organizations gain accurate, automated, and compliant tracking of employee work hours, leading to better efficiency, transparency, and workforce productivity.');
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('time-attendance', 'Accurate Tracking, Smarter Workforce Management and', 'Effective workforce management begins with precise attendance tracking. Our Time & Attendance module ensures organizations capture real-time data while simplifying scheduling and compliance.', 'center', 'none', 'bg-white', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('time-attendance', 'Real-Time Attendance Capture', 'From biometric devices to mobile check-ins, the system integrates multiple methods of recording attendance, ensuring accuracy and minimizing manual errors. Employees’ clock-in and clock-out records are instantly available for review.', 'center', 'none', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('time-attendance', 'Smarter Scheduling', 'Supervisors can plan and manage shifts, overtime, and rosters with ease. The module helps balance workloads, avoid scheduling conflicts, and ensure optimal resource allocation.', 'center', 'none', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('time-attendance', 'Policy and Compliance Support', 'Rules for working hours, overtime, rest days, and public holidays are built in, ensuring that attendance data aligns with company policy and statutory requirements.', 'center', 'none', 'bg-slate-50', 4);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('time-attendance', 'Integrated with Payroll and Leave', 'Attendance data flows directly into Payroll and Leave Management, ensuring correct pay calculations and reducing discrepancies. This integration eliminates redundant work and builds trust among employees.', 'center', 'none', 'bg-white', 5);
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status, outro_text) VALUES ('recruitment', 'Recruitment', 'End-to-end recruitment system managing job requisitions, applicants, interviews, and budgets with analytics for efficient hiring and workforce planning.', '/images/hrsm-modules/recruitment.png', 'published', 'With Recruitment, organizations can reduce hiring delays, control costs, and build stronger teams by leveraging an efficient and fully integrated recruitment system.');
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('recruitment', 'Smarter Hiring, Better Talent Acquisition', 'Finding and hiring the right people is crucial to business success. Our Recruitment module streamlines the process from requisition to onboarding, helping organizations secure top talent efficiently.', 'center', 'none', 'bg-white', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('recruitment', 'Streamlined Job Requisitions', 'Managers can create and track job requisitions with built-in approvals, ensuring every hiring request is aligned with business needs and budgets.', 'center', 'none', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('recruitment', 'Applicant Tracking Made Easy', 'The module manages applications, résumés, and candidate profiles in a centralized database. Recruiters can shortlist, schedule interviews, and track progress with clear visibility at every stage.', 'center', 'none', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('recruitment', 'Cost and Analytics', 'Recruitment costs, advertising expenses, and hiring metrics are tracked in real time. Analytics help measure time-to-hire, cost-per-hire, and recruitment effectiveness, enabling data-driven decisions.', 'center', 'none', 'bg-slate-50', 4);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('recruitment', 'Smooth Onboarding Integration', 'Once hired, candidate information flows seamlessly into the Personnel Hub, eliminating duplication and ensuring a smooth transition from applicant to employee.', 'center', 'none', 'bg-white', 5);
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status, outro_text) VALUES ('loan-management', 'Loan Management', 'Flexible employee loan benefit system supporting multiple loan types, repayment schedules, and approvals, promoting financial wellness and employee retention.', '/images/hrsm-modules/loan_management.png', 'published', 'With Loan Management, organizations can offer meaningful financial support, simplify administration, and enhance employee well-being, making it a valuable benefit for attracting and retaining talent.');
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('loan-management', 'Supporting Employee Financial Wellness', 'Employee financial well-being is an important aspect of overall engagement. Our Loan Management module provides organizations with the tools to administer employee loan benefits seamlessly and transparently.', 'center', 'none', 'bg-white', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('loan-management', 'Flexible Loan Types', 'The module supports a variety of loan categories, including personal, housing, vehicle, and education loans—each configurable according to company policies and entitlements.', 'center', 'none', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('loan-management', 'Automated Processing', 'From application to approval and repayment, Loan Management streamlines the entire process. Built-in rules manage eligibility, repayment schedules, and interest rates, reducing manual intervention and errors.', 'center', 'none', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('loan-management', 'Transparent Tracking', 'Employees can view loan balances, repayment history, and upcoming deductions through self-service access. This transparency builds trust and reduces queries to HR.', 'center', 'none', 'bg-slate-50', 4);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('loan-management', 'Integrated with Payroll', 'Loan repayments are automatically deducted during payroll processing, ensuring accuracy and timeliness without additional effort for HR administrators.', 'center', 'none', 'bg-white', 5);
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status, outro_text) VALUES ('loan-interest-subsidy', 'Loan Interest Subsidy', 'Automated management of employer-subsidized loan interest benefits, ensuring transparency, accuracy, and compliance while supporting employee financial wellbeing initiatives effectively.', '/images/hrsm-modules/loan_interest_subsidy.png', 'published', 'With Loan Interest Subsidy, organizations can deliver impactful financial benefits, simplify administration, and enhance overall employee satisfaction as part of a competitive HR package.');
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('loan-interest-subsidy', 'Enhancing Employee Benefits', 'For organizations that go beyond offering loans, our Loan Interest Subsidy module helps manage employer-subsidized interest benefits with accuracy and transparency.', 'center', 'none', 'bg-white', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('loan-interest-subsidy', 'Supporting Financial Well-Being', 'By subsidizing part or all of loan interest, companies provide employees with meaningful financial relief. This benefit strengthens loyalty and promotes long-term retention.', 'center', 'none', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('loan-interest-subsidy', 'Automated Calculations', 'The module handles complex calculations for subsidized interest amounts, repayment schedules, and eligibility criteria—removing the burden of manual tracking and reducing errors.', 'center', 'none', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('loan-interest-subsidy', 'Clear Employee Visibility', 'Employees gain full visibility of their subsidy entitlements and repayment details through self-service, ensuring transparency and minimizing HR queries.', 'center', 'none', 'bg-slate-50', 4);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('loan-interest-subsidy', 'Integrated with Payroll and Loan Management', 'Subsidized interest amounts are automatically reflected in payroll deductions and reports. Seamless integration ensures accuracy while maintaining compliance with company policies and audit requirements.', 'center', 'none', 'bg-white', 5);
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status, outro_text) VALUES ('gis-ghs', 'GIS & GHS', 'Comprehensive module managing Group Insurance and Hospitalization benefits, ensuring accurate coverage, claims processing, and compliance with organizational policies.', '/images/hrsm-modules/GIS_&_GHS.png', 'published', 'With GIS & GHS, organizations can deliver peace of mind, reduce administrative complexity, and strengthen employee loyalty by ensuring protection when it matters most.');
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('gis-ghs', 'Protecting Employees with Comprehensive Coverage', 'Employee well-being extends beyond the workplace. Our GIS & GHS module helps organizations manage Group Insurance Scheme (GIS) and Group Hospitalization Scheme (GHS) benefits with efficiency and accuracy.', 'center', 'none', 'bg-white', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('gis-ghs', 'Centralized Policy Management', 'All insurance and hospitalization policies are stored in one place, making it easy to track coverage, eligibility, and renewal dates.', 'center', 'none', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('gis-ghs', 'Employee Coverage Records', 'HR can maintain detailed records of each employee’s coverage, beneficiaries, and entitlements, ensuring transparency and minimizing disputes.', 'center', 'none', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('gis-ghs', 'Claims and Premium Tracking', 'The module manages premium payments, claims submissions, and reimbursements, giving both HR and employees a clear view of transactions and balances.', 'center', 'none', 'bg-slate-50', 4);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('gis-ghs', 'Compliance and Reporting', 'Built-in reporting tools help ensure compliance with organizational policies and insurance provider requirements, while also supporting audits and financial reconciliations.', 'center', 'none', 'bg-white', 5);
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status, outro_text) VALUES ('esos-management', 'ESOS Management', 'Streamlined administration of stock option grants, vesting schedules, and compliance, empowering organizations to reward employees and retain high-value talent', '/images/hrsm-modules/ESOS_management.png', 'published', 'With ESOS Management, organizations can align employee interests with business growth, enhance retention, and reduce administrative complexity in managing stock option schemes.');
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('esos-management', 'Empowering Employees with Ownership Opportunities', 'Employee Share Option Schemes (ESOS) are a powerful way to reward and retain talent. Our ESOS Management module streamlines the administration of stock option grants and vesting schedules with precision.', 'center', 'none', 'bg-white', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('esos-management', 'Simplified Grant Administration', 'Organizations can easily manage the granting of stock options, track allocations, and monitor employee eligibility, all within a centralized system.', 'center', 'none', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('esos-management', 'Vesting Schedule Tracking', 'Automated tools handle vesting timelines, ensuring employees receive their entitlements accurately and on time, without the risk of manual errors.', 'center', 'none', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('esos-management', 'Employee Transparency', 'Through self-service, employees can view their option grants, vesting status, and exercise rights, promoting transparency and boosting motivation.', 'center', 'none', 'bg-slate-50', 4);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('esos-management', 'Compliance and Reporting', 'The module provides audit-ready reports to ensure compliance with corporate governance and regulatory requirements, while also supporting strategic decision-making.', 'center', 'none', 'bg-white', 5);
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status, outro_text) VALUES ('espp-management', 'ESPP Management', 'Enables local employees to purchase global listed company shares through payroll deductions, promoting ownership, loyalty, and alignment with organizational success.', '/images/hrsm-modules/ESPP_management.png', 'published', 'With ESPP Management, organizations can extend global benefits, empower local employees, and strengthen retention by fostering a shared sense of ownership across borders.');
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('espp-management', 'Enabling Global Share Participation', 'For multinational organizations, Employee Share Purchase Plans (ESPP) provide local employees with access to global ownership opportunities. Our ESPP Management module simplifies administration while ensuring compliance with international frameworks.', 'center', 'none', 'bg-white', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('espp-management', 'Global Share Access', 'Employees can participate in purchasing shares of the parent or holding company listed overseas, often at discounted prices through payroll deductions.', 'center', 'none', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('espp-management', 'Automated Contribution Tracking', 'The module manages subscription amounts, deductions, and purchase cycles automatically, ensuring accuracy and transparency throughout the process.', 'center', 'none', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('espp-management', 'Employee Empowerment', 'Through self-service, employees can view contribution history, share purchases, and accumulated holdings, building stronger engagement and a sense of global belonging.', 'center', 'none', 'bg-slate-50', 4);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('espp-management', 'Compliance and Reporting', 'The module supports compliance with both local regulations and international stock exchange requirements, while providing audit-ready reports for HR and finance teams.', 'center', 'none', 'bg-white', 5);
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status, outro_text) VALUES ('training-management', 'Training Management', 'Comprehensive training administration system managing courses, schedules, budgets, and analytics, supporting skill development, compliance, and continuous workforce learning initiatives.', '/images/hrsm-modules/training_management.png', 'published', 'With Training Management, organizations can maximize ROI on learning, strengthen employee capabilities, and cultivate a culture of continuous development.');
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('training-management', 'Driving Growth Through Learning', 'Employee development is the foundation of organizational success. Our Training Management module provides end-to-end administration of training programs, ensuring structured growth and measurable results.', 'center', 'none', 'bg-white', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('training-management', 'Centralized Course Administration', 'Maintain a complete database of internal and external courses, including details such as course type, duration, provider, cost, and trainers.', 'center', 'none', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('training-management', 'Training Calendar & Planning', 'HR can build yearly training calendars, track planned sessions, and manage nominations and registrations with ease, ensuring organized execution of learning initiatives.', 'center', 'none', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('training-management', 'Attendance & Cost Tracking', 'The module captures attendance, participant status, and all associated costs—from course fees to travel and accommodation—giving full visibility of training investments.', 'center', 'none', 'bg-slate-50', 4);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('training-management', 'Integrated with Competency & TNA', 'Training is directly linked to competencies and Training Needs Analysis, ensuring every program addresses actual skill gaps and organizational goals.', 'center', 'none', 'bg-white', 5);
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status, outro_text) VALUES ('competency-management', 'Competency Management', 'Tracks and assesses employee skills, identifies gaps, and supports targeted development to align workforce competencies with strategic organizational objectives.', '/images/hrsm-modules/competency_management.png', 'published', 'With Competency Management, organizations can build a future-ready workforce, align skills with strategy, and enhance performance through targeted capability development.');
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('competency-management', 'Building Skills for the Future', 'Strong organizations are built on strong capabilities. Our Competency Management module enables companies to track, assess, and develop employee skills aligned with business goals.', 'center', 'none', 'bg-white', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('competency-management', 'Centralized Competency Framework', 'Define and manage organizational competencies across roles, departments, and levels. Ensure employees are evaluated against consistent and transparent benchmarks.', 'center', 'none', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('competency-management', 'Gap Analysis', 'Identify skill gaps by comparing current employee competencies with required standards. This helps prioritize development plans and align resources effectively.', 'center', 'none', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('competency-management', 'Personalized Development Plans', 'The module integrates with Training Management, ensuring targeted learning opportunities are assigned to close competency gaps and strengthen workforce readiness.', 'center', 'none', 'bg-slate-50', 4);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('competency-management', 'Strategic Insights', 'Comprehensive reports and dashboards highlight strengths, weaknesses, and trends in organizational skills, supporting data-driven workforce planning and succession management.', 'center', 'none', 'bg-white', 5);
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status, outro_text) VALUES ('training-needs-analysis', 'Training Needs Analysis (TNA)', 'Identifies training gaps by comparing competencies with requirements, enabling organizations to align learning programs with workforce and business needs.', '/images/hrsm-modules/training_needs_analysis.png', 'published', 'With Training Needs Analysis, organizations can invest in the right skills, maximize training ROI, and build a workforce prepared for future challenges.');
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('training-needs-analysis', 'Aligning Skills with Business Goals', 'Effective training starts with identifying the right needs. Our Training Needs Analysis (TNA) module helps organizations systematically uncover skill gaps and align learning initiatives with strategic priorities.', 'center', 'none', 'bg-white', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('training-needs-analysis', 'Data-Driven Assessment', 'The module evaluates employee competencies against job requirements, identifying gaps that may affect performance, productivity, or future growth.', 'center', 'none', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('training-needs-analysis', 'Targeted Training Plans', 'By pinpointing specific needs, HR can design focused training programs that directly address gaps, ensuring maximum impact from learning investments.', 'center', 'none', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('training-needs-analysis', 'Seamless Integration', 'TNA works hand-in-hand with Training Management and Competency Management, ensuring every program is aligned to organizational goals and individual development.', 'center', 'none', 'bg-slate-50', 4);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('training-needs-analysis', 'Strategic Workforce Planning', 'Reports and analytics provide insights into workforce readiness, helping leaders prioritize critical skill areas and allocate training budgets effectively.', 'center', 'none', 'bg-white', 5);
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status) VALUES ('performance-management', 'Performance Management', 'Robust system supporting 360-degree assessments, multiple appraisers, customizable appraisal forms, and weighted scoring, ensuring fair evaluations and continuous improvement.', '/images/hrsm-modules/performance_management.png', 'published');
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('performance-management', 'Driving Success Through Alignment', 'High-performing organizations align individual contributions with business strategy. Our Performance Management module empowers HR and managers with robust tools to set goals, evaluate fairly, and nurture growth.', 'center', 'none', 'bg-white', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('performance-management', 'Goal Setting & Alignment', 'Employees and managers can define measurable goals tied to organizational strategy, ensuring alignment across all levels of the workforce.', 'center', 'none', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('performance-management', 'Flexible Assessments', 'The module supports up to 12 assessments per year, allowing regular monitoring and feedback. Weighted scoring can be applied so interim reviews contribute appropriately to the final assessment.', 'center', 'none', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('performance-management', 'Multi-Appraiser & 360° Reviews', 'Performance can be evaluated by multiple appraisers, including peers, subordinates, and supervisors, enabling 360-degree feedback for a well-rounded perspective on employee contributions.', 'center', 'none', 'bg-slate-50', 4);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('performance-management', 'Fully Customizable Forms', 'HR can design user-definable appraisal forms, with different templates tailored for various employee groups, ensuring relevance and fairness across roles.', 'center', 'none', 'bg-white', 5);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('performance-management', 'Development & Recognition', 'Results can be directly linked to training, promotions, and rewards, reinforcing a culture of accountability, growth, and recognition.', 'center', 'none', 'bg-slate-50', 6);
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status, outro_text) VALUES ('employee-self-service', 'Employee Self Service (ESS)', 'Empowers employees to access records, submit requests, and update details independently, reducing HR workload while enhancing transparency and employee engagement.', '/images/hrsm-modules/employee_self_service.png', 'published', 'With Employee Self Service, organizations can empower employees, improve efficiency, and transform HR from administrative to strategic.');
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('employee-self-service', 'Empowering Employees, Reducing HR Workload', 'Modern HR is about empowerment. Our Employee Self Service (ESS) module puts control in the hands of employees, reducing administrative burdens while enhancing transparency and accessibility.', 'center', 'none', 'bg-white', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('employee-self-service', 'Anytime, Anywhere Access', 'Employees can update personal details, view payslips, check leave balances, submit claims, and track loan records directly from their ESS portal.', 'center', 'none', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('employee-self-service', 'Streamlined HR Processes', 'By decentralizing routine tasks such as leave applications, claim submissions, and training registrations, ESS eliminates paperwork and speeds up approval workflows.', 'center', 'none', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('employee-self-service', 'Transparency & Engagement', 'Employees gain visibility into their records—attendance, benefits, performance reviews, and more—strengthening trust and fostering a sense of ownership in HR processes.', 'center', 'none', 'bg-slate-50', 4);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('employee-self-service', 'Reduced HR Workload', 'By shifting routine requests and inquiries to self-service, HR teams are free to focus on higher-value initiatives that drive organizational growth.', 'center', 'none', 'bg-white', 5);
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status, outro_text) VALUES ('mobile-app', 'Mobile App', 'Mobile-first platform providing on-the-go access to HR services, approvals, and notifications, enhancing convenience, productivity, and workforce connectivity anytime.', '/images/hrsm-modules/mobile_app.png', 'published', 'With the Mobile App, organizations can make HR services accessible anytime, boost responsiveness, and empower a more connected workforce.');
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('mobile-app', 'HR in the Palm of Your Hand', 'Today’s workforce expects flexibility and instant access. Our Mobile App brings the full power of HR services directly to employees’ smartphones, ensuring HR is always within reach.', 'center', 'none', 'bg-white', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('mobile-app', 'Anytime, Anywhere Access', 'Employees can apply for leave, submit claims, check payslips, view attendance records, and track loan balances, all on the go.', 'center', 'none', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('mobile-app', 'Real-Time Notifications', 'Push notifications keep employees updated on approvals, pending tasks, and important HR announcements, ensuring no request or update is ever missed.', 'center', 'none', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('mobile-app', 'Manager Convenience', 'Supervisors can review and approve requests instantly, reducing bottlenecks and enabling faster decision-making, even outside the office.', 'center', 'none', 'bg-slate-50', 4);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('mobile-app', 'Secure & Seamless Integration', 'Built to work seamlessly with the HR system, the app ensures data accuracy and security while delivering a smooth, user-friendly experience.', 'center', 'none', 'bg-white', 5);
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status, outro_text) VALUES ('bi-dashboard-analytics', 'BI Dashboard Analytics', 'Transforms HR data into interactive dashboards and insights, enabling real-time monitoring, predictive analysis, and data-driven strategic workforce decisions.', '/images/hrsm-modules/BI_dashboard_analytics.png', 'published', 'With BI Dashboard Analytics, organizations can turn HR data into strategic intelligence, driving efficiency, foresight, and stronger workforce management.');
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('bi-dashboard-analytics', 'Turning HR Data into Decisions', 'Data is only powerful when it drives action. Our BI Dashboard Analytics module transforms complex HR data into clear, actionable insights for smarter decision-making.', 'center', 'none', 'bg-white', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('bi-dashboard-analytics', 'Real-Time Insights', 'Interactive dashboards display live HR metrics—from headcount trends to attrition analysis—enabling leaders to monitor organizational health at a glance.', 'center', 'none', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('bi-dashboard-analytics', 'Customizable Dashboards', 'Tailor dashboards by department, role, or strategic priority, ensuring every manager sees the data most relevant to their responsibilities.', 'center', 'none', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('bi-dashboard-analytics', 'Predictive Analytics', 'Go beyond historical reports with advanced analytics that help identify risks, forecast trends, and support proactive workforce planning.', 'center', 'none', 'bg-slate-50', 4);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('bi-dashboard-analytics', 'Data-Driven Decisions', 'By consolidating payroll, leave, attendance, training, and performance data, the module empowers management to make faster, evidence-based HR and business decisions.', 'center', 'none', 'bg-white', 5);
INSERT INTO public.hrms_modules (slug, name, tagline, image_src, status) VALUES ('module-configurator', 'Configurator', 'Easily assemble and name new modules on the fly, assign access rights, and streamline HR processes with unmatched flexibility and control', '/images/hrsm-modules/configurator.png', 'published');
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('module-configurator', 'Redefining Flexibility in HR Systems', 'Our HR system features a powerful Configurator module, designed to deliver unmatched flexibility and control. With Configurator, organizations can assemble and name new modules on the fly, tailoring the system to specific business needs without waiting for custom development.', 'center', 'none', 'bg-white', 1);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('module-configurator', 'Built on Object-Oriented Architecture', 'The secret lies in our object-oriented design. Every screen and report in the system is treated as an independent object, capable of running on its own. This approach allows users to pluck any object—whether a screen or report—and group them together to form a brand-new module, complete with its own name, access rights, and seamless integration into the HR ecosystem.', 'center', 'none', 'bg-slate-50', 2);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('module-configurator', 'Simplifying User Experience', 'Configurator also enhances usability for new recruits. Instead of navigating the full HR system, users can be assigned personalized modules that contain only the functions they need, making onboarding faster and reducing learning curves.', 'center', 'none', 'bg-white', 3);
INSERT INTO public.hrms_features (module_slug, title, description, layout, media_type, bg_color, order_index) VALUES ('module-configurator', 'Eliminating Process Gaps', 'Beyond personalization, Configurator can be used to create process-specific checklists, ensuring critical payroll or HR steps are not missed. By grouping related tasks into logical modules, organizations can streamline workflows and maintain compliance effortlessly.', 'center', 'none', 'bg-slate-50', 4);
